# Generated by Django 5.2.15 on 2026-06-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_power', models.FloatField()),
                ('blue', models.IntegerField()),
                ('clock_speed', models.FloatField()),
                ('dual_sim', models.IntegerField()),
                ('fc', models.FloatField()),
                ('four_g', models.IntegerField()),
                ('int_memory', models.FloatField()),
                ('m_dep', models.FloatField()),
                ('mobile_wt', models.FloatField()),
                ('n_cores', models.FloatField()),
                ('pc', models.FloatField()),
                ('px_height', models.FloatField()),
                ('px_width', models.FloatField()),
                ('ram', models.FloatField()),
                ('sc_h', models.FloatField()),
                ('sc_w', models.FloatField()),
                ('talk_time', models.FloatField()),
                ('three_g', models.IntegerField()),
                ('touch_screen', models.IntegerField()),
                ('wifi', models.IntegerField()),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
